### ISSUE TITLE
CC_MD5_Final and     webView.configuration.preferences.javaEnabled = true

### ISSUE THREAD

**Issue by zengchanghuan** [TencentCloud/chat-demo-flutter#10]
当前电脑版本：
3.2 GHz 六核Intel Core i7 
13.2.1 (22D68)

Launching lib/main.dart on macOS in debug mode...
Running pod install...
Building macOS application...
/Users/zengch/.pub-cache/hosted/pub.dev/photo_manager-2.6.0/macos/Classes/core/PMMD5Utils.m:10:5: warning: 'CC_MD5' is deprecated: first deprecated in macOS 10.15 - This function is cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger). [-Wdeprecated-declarations]
    CC_MD5(original_str, (uint) strlen(original_str), digest);
    ^
In module 'CommonCrypto' imported from /Users/zengch/.pub-cache/hosted/pub.dev/photo_manager-2.6.0/macos/Classes/core/PMMD5Utils.h:2:
extern unsigned char *CC_MD5(const void *data, CC_LONG len, unsigned char *md)
                      ^
/Users/zengch/.pub-cache/hosted/pub.dev/photo_manager-2.6.0/macos/Classes/core/PMMD5Utils.m:21:5: warning: 'CC_MD5' is deprecated: first deprecated in macOS 10.15 - This function is cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger). [-Wdeprecated-declarations]
    CC_MD5(original_str, (uint) strlen(original_str), digest);
    ^
In module 'CommonCrypto' imported from /Users/zengch/.pub-cache/hosted/pub.dev/photo_manager-2.6.0/macos/Classes/core/PMMD5Utils.h:2:
extern unsigned char *CC_MD5(const void *data, CC_LONG len, unsigned char *md)
                      ^
/Users/zengch/.pub-cache/hosted/pub.dev/photo_manager-2.6.0/macos/Classes/core/PMMD5Utils.m:70:5: warning: 'CC_MD5_Init' is deprecated: first deprecated in macOS 10.15 - This function is cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger). [-Wdeprecated-declarations]
    CC_MD5_Init(&hashObject);
    ^
In module 'CommonCrypto' imported from /Users/zengch/.pub-cache/hosted/pub.dev/photo_manager-2.6.0/macos/Classes/core/PMMD5Utils.h:2:
extern int CC_MD5_Init(CC_MD5_CTX *c)
           ^
/Users/zengch/.pub-cache/hosted/pub.dev/photo_manager-2.6.0/macos/Classes/core/PMMD5Utils.m:88:9: warning: 'CC_MD5_Update' is deprecated: first deprecated in macOS 10.15 - This function is cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger). [-Wdeprecated-declarations]
        CC_MD5_Update(&hashObject, (const void *) buffer, (CC_LONG) readBytesCount);
        ^
In module 'CommonCrypto' imported from /Users/zengch/.pub-cache/hosted/pub.dev/photo_manager-2.6.0/macos/Classes/core/PMMD5Utils.h:2:
extern int CC_MD5_Update(CC_MD5_CTX *c, const void *data, CC_LONG len)
           ^
/Users/zengch/.pub-cache/hosted/pub.dev/photo_manager-2.6.0/macos/Classes/core/PMMD5Utils.m:96:5: warning: 'CC_MD5_Final' is deprecated: first deprecated in macOS 10.15 - This function is cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger). [-Wdeprecated-declarations]
    CC_MD5_Final(digest, &hashObject);
    ^
In module 'CommonCrypto' imported from /Users/zengch/.pub-cache/hosted/pub.dev/photo_manager-2.6.0/macos/Classes/core/PMMD5Utils.h:2:
extern int CC_MD5_Final(unsigned char *md, CC_MD5_CTX *c)
           ^
5 warnings generated.
/Users/zengch/.pub-cache/hosted/pub.dev/desktop_webview_window_for_is-0.2.4/macos/Classes/WebViewLayoutController.swift:90:39: warning: 'javaEnabled' was deprecated in macOS 10.15: Java is no longer supported
    webView.configuration.preferences.javaEnabled = true
                                      ^
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')

**Comment by RoleWong** [comment]
看起来您截图的全都是warning，由于版本导致的。不会影响正常使用。如果无法正常使用，请补充额外贴一下error报错信息。谢谢
