### ISSUE TITLE
包名冲突

### ISSUE THREAD

**Issue by LinYingQiang** [TencentCloud/chat-demo-flutter#12]
1.本地flutter版本3.10.5
2.dart.core.Duration类和tuicore_define.Duration枚举命名冲突
![20230630224029](https://github.com/TencentCloud/chat-demo-flutter/assets/13882401/83778f9e-cdd9-48e5-8e1c-2c7394b4df05)

**Comment by LinYingQiang** [comment]
1.通过import 'package:tencent_cloud_uikit_core/tencent_cloud_uikit_core.dart' hide Duration;无效
2.直接给系统包名设置 import 'dart:core' as Core; 别名工程量太大，
有什么方案可以解决这个问题吗？

**Comment by RobotJohns** [comment]
直接屏蔽

**Comment by RoleWong** [comment]
您好，此问题我们已收到，已转达相关同事帮忙紧急修复中，修复完成后，在此跟进进展。非常抱歉给您带来的不便。

**Comment by RoleWong** [comment]
请重新获取项目依赖并尝试. 如果还是不行, 请手动将项目内 pubspec.lock 里面的tencent_cloud_uikit_core 升级至1.0.6版本. 谢谢

**Comment by RoleWong** [comment]
请重新获取项目依赖并尝试. 如果还是不行, 请手动将项目内 pubspec.lock 里面的tencent_cloud_uikit_core 升级至1.0.6版本. 谢谢
