### ISSUE TITLE
拍摄照片发送出现异常

### ISSUE THREAD

**Issue by liuhongda91** [TencentCloud/chat-demo-flutter#14]
拍摄完照片显示在聊天页面会出现图片缩小的情况

The following assertion was thrown during performLayout():
'package:flutter/src/rendering/box.dart': Failed assertion: line 321 pos 12: 'width > 0.0': is not true.

**Comment by 1284115201** [comment]
我也是，测试那边反馈这个问题，可有解决方案？

**Comment by RoleWong** [comment]
您好, 此问题已修复. 请更新至最新的 Demo 代码源码. 如果使用 UIKit, 请更新至2.2.0版本. 谢谢

**Comment by RoleWong** [comment]
> 我也是，测试那边反馈这个问题，可有解决方案？

您好, 此问题已修复. 请更新至最新的 Demo 代码源码. 如果使用 UIKit, 请更新至2.2.0版本. 谢谢
