### ISSUE TITLE
chrome上可以跑起来， 在macos和ios模拟器上报错

### ISSUE THREAD

**Issue by Jackelson** [TencentCloud/chat-demo-flutter#20]
Xcode无法 查找与“FN2V63AD2J/com.tencent.im.flutter.uikit_Development_SignProvision_MAC_OS”匹配的任何配置文件。 安装配置文件（通过将其拖放到 Xcode 的停靠项上）或在目标编辑器的“签名和功能”选项卡中选择不同的配置文件。

**Comment by RoleWong** [comment]
楼上同事已回复
