### ISSUE TITLE
ios pod install报错

### ISSUE THREAD

**Issue by xiaoshuimao** [TencentCloud/chat-demo-flutter#21]
![image](https://github.com/TencentCloud/chat-demo-flutter/assets/6658087/47f6c24d-e2f7-4be3-b8fa-1db7e103ced0)

**Comment by hexingcheng** [comment]
看报错提示，应该更新repo就能获取到7.8
执行pod update repo，再进行pod install就行

**Comment by RoleWong** [comment]
可以尝试手动删除 podfile.lock 后执行 pod install --repo-update
