### ISSUE TITLE
Error running pod install Error launching application on iPhone 15 Pro.

### ISSUE THREAD

**Issue by dd9913762113** [TencentCloud/chat-demo-flutter#22]
demo下载下来就用不了，怎么搞
Error running pod install
Error launching application on iPhone 15 Pro.

**Comment by hexingcheng** [comment]
可以在zhiliao.qq.com里提供更加详细的错误，我们看一下

**Comment by RoleWong** [comment]
可以尝试手动删除 podfile.lock 后执行 pod install --repo-update
