### ISSUE TITLE
v2 demo 构建错误

### ISSUE THREAD

**Issue by JxJPu9bD** [TencentCloud/chat-demo-flutter#28]
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.2, on Microsoft Windows [版本 10.0.19045.4780], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.6) 
[√] Android Studio (version 2024.1)
[√] IntelliJ IDEA Ultimate Edition (version 2022.2)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

![image](https://github.com/user-attachments/assets/cb7c95a5-cc42-473f-8bf4-6839659ec06b)
我的开发环境没有问题

但是无论android还是ios都会有这个错误, 疑似内部的 tencent_extended_text 实现错误,
![image](https://github.com/user-attachments/assets/3bab1620-273a-43fb-a2a0-e4f64c2eadef)

如果我的flutter版本太高, 请问我应该使用哪个版本

尝试 3.19 3.16 等版本无法满足依赖

尝试更新 extended_text 不行

```
Resolving dependencies... 
Because tencent_cloud_chat_message 1.6.1 depends on extended_text_field ^15.0.0 and no versions of tencent_cloud_chat_message match >1.6.1 <2.0.0, tencent_cloud_chat_message ^1.6.1 requires extended_text_field ^15.0.0.
So, because tencent_cloud_chat_demo depends on both tencent_cloud_chat_message ^1.6.1 and extended_text_field 16.0.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on tencent_cloud_chat_message: flutter pub add tencent_cloud_chat_message:^1.3.1
```

**Comment by JxJPu9bD** [comment]
我用 v2, 提交hash ffe1e0e
使用 flutter 3.22.3 构建成功了

flutter 3.22.0 都不行
请你们更新下readme吧

**Comment by flyer1b** [comment]
Flutter version 3.24.3 不行，一样的报错

**Comment by flyer1b** [comment]
> 我用 v2, 提交hash [ffe1e0e](https://github.com/TencentCloud/chat-demo-flutter/commit/ffe1e0ee6744a7115b67db48855b2173319488e0) 使用 flutter 3.22.3 构建成功了
> 
> flutter 3.22.0 都不行 请你们更新下readme吧

你是怎么解决的，我3.24.3都不行

**Comment by JxJPu9bD** [comment]
> > 我用 v2, 提交hash [ffe1e0e](https://github.com/TencentCloud/chat-demo-flutter/commit/ffe1e0ee6744a7115b67db48855b2173319488e0) 使用 flutter 3.22.3 构建成功了
> > flutter 3.22.0 都不行 请你们更新下readme吧
> 
> 你是怎么解决的，我3.24.3都不行

就用 3.22.3  新了旧了都不行, 这是他们官方客服给的版本
