### ISSUE TITLE
使用fire_base 初始化失败

### ISSUE THREAD

**Issue by muggleXin** [TencentCloud/chat-demo-flutter#3]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.5.1 21G83 darwin-arm, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2021.2)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (3 available)
[✓] HTTP Host Availability

依赖版本
firebase_core: ^1.11.0
tim_ui_kit_calling_plugin: ^1.0.6+4
tim_ui_kit_push_plugin: ^2.0.2+3

Restarted application in 1,170ms.
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:199:7)
<asynchronous suspension>
#1      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:29:44)
<asynchronous suspension>
#2      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
<asynchronous suspension>
#3      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:31)
<asynchronous suspension>
#4      Global.init (package:flutter_goufw/global.dart:19:5)
<asynchronous suspension>

一旦引入了tim_ui_kit_calling_plugin、tim_ui_kit_push_plugin 初始化firebase就会卡在这里

**Comment by RoleWong** [comment]
本问题在TG群中跟进处理。感谢您的支持～
