### ISSUE TITLE
web下个人中心出现一直加载动画

### ISSUE THREAD

**Issue by skyfall** [TencentCloud/chat-demo-flutter#6]
1.登录成功后选择登出
2.不要刷新页面登入相同账号
3.点击【我的】 导航栏

出现一直加载的动画效果

<img width="477" alt="image" src="https://user-images.githubusercontent.com/6636717/232809350-dbf5fec4-e898-4d29-b871-a3f83e82fe63.png">

**Comment by RoleWong** [comment]
问题已复现，我们来优化。感谢反馈～

**Comment by RoleWong** [comment]
感谢您的耐心等待。此问题已在 tencent_cloud_chat_uikit: ^2.1.2 版本中修复。欢迎您重新体验 Demo 获取最新代码。
